# Generated by Django 5.0.4 on 2024-05-01 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('Naqd pul', 'Naqd pul'), ('Kartadan', 'Kartadan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('Tasdiqlanmoqda', 'Tasdiqlanmoqda'), ('Tasdiqlanmadi', 'Tasdiqlanmadi'), ('Tasdiqlandi', 'Tasdiqlandi')], default='Tasdiqlanmoqda'),
        ),
        migrations.CreateModel(
            name='PaymentsCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('check_img', models.ImageField(upload_to='checks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsCheck', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
