# Generated by Django 5.0.4 on 2024-05-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_payments_payment_type_alter_payments_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscheck',
            name='status',
            field=models.CharField(choices=[('Tasdiqlanmoqda', 'Tasdiqlanmoqda'), ('Tasdiqlandi', 'Tasdiqlandi')], default='Tasdiqlanmoqda', max_length=30),
        ),
    ]
