# Generated by Django 5.0.4 on 2024-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_paymentscheck_check_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='check_img',
            field=models.ImageField(blank=True, null=True, upload_to='checks/'),
        ),
        migrations.AddField(
            model_name='payments',
            name='check_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('Kutayotgan', 'Kutayotgan'), ('Qaytarilgan', 'Qaytarilgan'), ('Tasdiqlangan', 'Tasdiqlangan')], default='Kutayotgan'),
        ),
        migrations.AlterField(
            model_name='paymentscheck',
            name='status',
            field=models.CharField(choices=[('Kutayotgan', 'Kutayotgan'), ('Tasdiqlangan', 'Tasdiqlangan')], default='Kutayotgan', max_length=30),
        ),
    ]
